apiVersion: mailgun.com/v1alpha1
kind: MailgunRoute
metadata:
  name: example-mailgunroute
spec:
  domain: sandboxdf4d5910068941b7a4993947915e8393.mailgun.org
  secretName: mailgun-secret
  expression: match_recipient(".*@bar.com")
  priority: 0
  actions:
    - forward("mailbox@myapp.com")
    - forward("http://myapp.com/messages")