apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mailgundomains.mailgun.com
spec:
  group: mailgun.com
  names:
    kind: MailgunDomain
    listKind: MailgunDomainList
    plural: mailgundomains
    singular: mailgundomain
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: MailgunDomain is the Schema for the mailgundomains API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MailgunDomainSpec defines the desired state of MailgunDomain
          properties:
            apiKey:
              type: string
            dkim_key_size:
              type: integer
            domain:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
            force_dkim_authority:
              type: boolean
            ips:
              items:
                type: string
              minItems: 0
              type: array
            password:
              type: string
            spamAction:
              type: string
            webScheme:
              type: string
            wildcard:
              type: boolean
          required:
          - apiKey
          - domain
          type: object
        status:
          description: MailgunDomainStatus defines the observed state of MailgunDomain
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
