apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mailgunwebhooks.mailgun.com
spec:
  group: mailgun.com
  names:
    kind: MailgunWebhook
    listKind: MailgunWebhookList
    plural: mailgunwebhooks
    singular: mailgunwebhook
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: MailgunWebhook is the Schema for the mailgunwebhooks API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MailgunWebhookSpec defines the desired state of MailgunWebhook
          properties:
            apiKey:
              type: string
            clicked:
              items:
                type: string
              maxItems: 3
              minItems: 0
              type: array
              uniqueItems: true
            domain:
              type: string
            opened:
              items:
                type: string
              maxItems: 3
              minItems: 0
              type: array
              uniqueItems: true
          required:
          - apiKey
          - domain
          type: object
        status:
          description: MailgunWebhookStatus defines the observed state of MailgunWebhook
          properties:
            clicked:
              items:
                type: string
              maxItems: 3
              minItems: 0
              type: array
              uniqueItems: true
            opened:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              items:
                type: string
              maxItems: 3
              minItems: 0
              type: array
              uniqueItems: true
          required:
          - clicked
          - opened
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
