// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MailgunDomain) DeepCopyInto(out *MailgunDomain) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MailgunDomain.
func (in *MailgunDomain) DeepCopy() *MailgunDomain {
	if in == nil {
		return nil
	}
	out := new(MailgunDomain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MailgunDomain) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MailgunDomainDnsRecord) DeepCopyInto(out *MailgunDomainDnsRecord) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MailgunDomainDnsRecord.
func (in *MailgunDomainDnsRecord) DeepCopy() *MailgunDomainDnsRecord {
	if in == nil {
		return nil
	}
	out := new(MailgunDomainDnsRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MailgunDomainList) DeepCopyInto(out *MailgunDomainList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MailgunDomain, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MailgunDomainList.
func (in *MailgunDomainList) DeepCopy() *MailgunDomainList {
	if in == nil {
		return nil
	}
	out := new(MailgunDomainList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MailgunDomainList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MailgunDomainSpec) DeepCopyInto(out *MailgunDomainSpec) {
	*out = *in
	if in.IPS != nil {
		in, out := &in.IPS, &out.IPS
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MailgunDomainSpec.
func (in *MailgunDomainSpec) DeepCopy() *MailgunDomainSpec {
	if in == nil {
		return nil
	}
	out := new(MailgunDomainSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MailgunDomainStatus) DeepCopyInto(out *MailgunDomainStatus) {
	*out = *in
	if in.SendingDnsRecord != nil {
		in, out := &in.SendingDnsRecord, &out.SendingDnsRecord
		*out = make([]MailgunDomainDnsRecord, len(*in))
		copy(*out, *in)
	}
	if in.ReceivingDnsRecord != nil {
		in, out := &in.ReceivingDnsRecord, &out.ReceivingDnsRecord
		*out = make([]MailgunDomainDnsRecord, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MailgunDomainStatus.
func (in *MailgunDomainStatus) DeepCopy() *MailgunDomainStatus {
	if in == nil {
		return nil
	}
	out := new(MailgunDomainStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MailgunRoute) DeepCopyInto(out *MailgunRoute) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MailgunRoute.
func (in *MailgunRoute) DeepCopy() *MailgunRoute {
	if in == nil {
		return nil
	}
	out := new(MailgunRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MailgunRoute) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MailgunRouteList) DeepCopyInto(out *MailgunRouteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MailgunRoute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MailgunRouteList.
func (in *MailgunRouteList) DeepCopy() *MailgunRouteList {
	if in == nil {
		return nil
	}
	out := new(MailgunRouteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MailgunRouteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MailgunRouteSpec) DeepCopyInto(out *MailgunRouteSpec) {
	*out = *in
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MailgunRouteSpec.
func (in *MailgunRouteSpec) DeepCopy() *MailgunRouteSpec {
	if in == nil {
		return nil
	}
	out := new(MailgunRouteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MailgunRouteStatus) DeepCopyInto(out *MailgunRouteStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MailgunRouteStatus.
func (in *MailgunRouteStatus) DeepCopy() *MailgunRouteStatus {
	if in == nil {
		return nil
	}
	out := new(MailgunRouteStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MailgunWebhook) DeepCopyInto(out *MailgunWebhook) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MailgunWebhook.
func (in *MailgunWebhook) DeepCopy() *MailgunWebhook {
	if in == nil {
		return nil
	}
	out := new(MailgunWebhook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MailgunWebhook) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MailgunWebhookList) DeepCopyInto(out *MailgunWebhookList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MailgunWebhook, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MailgunWebhookList.
func (in *MailgunWebhookList) DeepCopy() *MailgunWebhookList {
	if in == nil {
		return nil
	}
	out := new(MailgunWebhookList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MailgunWebhookList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MailgunWebhookSpec) DeepCopyInto(out *MailgunWebhookSpec) {
	*out = *in
	if in.Clicked != nil {
		in, out := &in.Clicked, &out.Clicked
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Complained != nil {
		in, out := &in.Complained, &out.Complained
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Delivered != nil {
		in, out := &in.Delivered, &out.Delivered
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Opened != nil {
		in, out := &in.Opened, &out.Opened
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PermanentFail != nil {
		in, out := &in.PermanentFail, &out.PermanentFail
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TemporaryFail != nil {
		in, out := &in.TemporaryFail, &out.TemporaryFail
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Unsubscribed != nil {
		in, out := &in.Unsubscribed, &out.Unsubscribed
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MailgunWebhookSpec.
func (in *MailgunWebhookSpec) DeepCopy() *MailgunWebhookSpec {
	if in == nil {
		return nil
	}
	out := new(MailgunWebhookSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MailgunWebhookStatus) DeepCopyInto(out *MailgunWebhookStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MailgunWebhookStatus.
func (in *MailgunWebhookStatus) DeepCopy() *MailgunWebhookStatus {
	if in == nil {
		return nil
	}
	out := new(MailgunWebhookStatus)
	in.DeepCopyInto(out)
	return out
}
