apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailgun-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mailgun-operator
  template:
    metadata:
      labels:
        name: mailgun-operator
    spec:
      serviceAccountName: mailgun-operator
      containers:
        - name: mailgun-operator
          # Replace this with the built image name
          image: whyse/mailgun-operator:v0.0.1
          command:
          - mailgun-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "mailgun-operator"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mailgun-operator
subjects:
- kind: ServiceAccount
  name: mailgun-operator
roleRef:
  kind: Role
  name: mailgun-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: mailgun-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - mailgun-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get
- apiGroups:
  - mailgun.com
  resources:
  - '*'
  - mailgundomains
  - mailgunroutes
  verbs:
  - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mailgun-operator
